---
- name: disableScriptLua
  become: true
  ansible.builtin.replace:
    path: /root/haproxy.cfg
    regexp: "^(lua-load /usr/local/etc/haproxy/srv-monitor.lua)$"
    replace: "#lua-load /usr/local/etc/haproxy/srv-monitor.lua"