---
- name: Verificar se container IXC está rodando
  shell: docker ps --format '{{ "{{.Names}}" }}' | grep devoz-ixc 
  register: ixc_status
  # ignore_errors: true

- name: Print result of IXC status
  ansible.builtin.debug:
    msg: "Result: {{ ixc_status }}"

- name: Print if is running
  ansible.builtin.debug:
    msg: "IXC is running"
  when: "'devoz-ixc' in ixc_status.stdout"