---
- name: Verificar se container IXC está rodando
  shell: docker ps --format '{{ "{{.Names}}" }}' | grep {{ item }} 
  register: containers_status
  loop: 
    - devoz-ixc
    - devoz-sgp 
  # ignore_errors: true

# - name: Verificar se container Sgp está rodando
#   shell: docker ps --format '{{ "{{.Names}}" }}' | grep devoz-sgp 
#   register: sgp_status

- name: Print result of IXC status
  ansible.builtin.debug:
    msg: "Result: {{ containers_status }}"

- name: Print if is running
  ansible.builtin.debug:
    msg: "IXC is running"
  when: "'devoz-ixc' in containers_status.stdout"

- name: Print if sgp is running
  ansible.builtin.debug:
    msg: "sgp is running"
  when: "'devoz-sgp' in containers_status.stdout"