---
- name: Verificar se container IXC está rodando
  shell: docker ps --format '{{ "{{.Names}}" }}'"
  register: ixc_status
  ignore_errors: true
  register: ixc_status

- name: Print result of IXC status
  ansible.builtin.debug:
    msg: "Result: {{ ixc_status }}"