---
- name: Job de tratamento de erro (on-failure)
  tasks:
    - name: Buscar detalhes do Job pai que falhou
      ansible.builtin.uri:
        url: "{{ tower_url }}/api/v2/jobs/{{ tower_parent_job_id }}/"
        method: GET
        headers:
          Authorization: "Bearer {{ tower_api_token }}"
          Content-Type: "application/json"
      register: api_response

- name: Extrair mensagem de erro
  ansible.builtin.set_fact:
    error_message: "{{ api_response.json.job_explanation | default('Erro desconhecido') }}"

- name: Exibir erro capturado
  ansible.builtin.debug:
    msg: "Erro no Job {{ tower_parent_job_id }}: {{ error_message }}"
