---
- name: Mostra TUDO que foi passado via extra vars
  ansible.builtin.debug:
    # msg: "{{ vars }} | map(attribute='stage')"
    # msg: " {{ vars | dict2items | selectattr('key', 'endswith', '_image') | list }}"
    msg: " {{ vars | dict2items | selectattr('key', 'match', '.*_image$') | list }}"
    register: image-var

- name: Mostra imgem
  ansible.builtin.debug:
    msg: "{{ image-var | map(attribute='value') | list }}"
