---
- name: verifica arq
  become: true
  ansible.builtin.stat:
    path: /etc/ssh/sshd_config.d/3231-cloud-init.conf
  register: file_exists

- name: Disable password authentication in SSH in 50-cloud-init.conf
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config.d/50-cloud-init.conf
    regexp: '^PasswordAuthentication yes'
    line: 'PasswordAuthentication no'
    backup: yes
  when: file_exists.stat.exists
  register: disable_pwd_auth_50_cloud_init_conf

- name: Disable password authentication in SSH in sshd_config
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PasswordAuthentication yes'
    line: 'PasswordAuthentication no'
    backup: yes
  when: not file_exists.stat.exists
  register: disable_pwd_auth_sshd_config

- name: Debug SSH configuration changes
  debug:
    msg: "sshd_config changed"
  when: disable_pwd_auth_sshd_config.changed

- name: Debug SSH configuration changes
  debug:
    msg: "50-cloud-init.conf changed"
  when: disable_pwd_auth_50_cloud_init_conf.changed
